config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses
  resources :users, only: [:index]
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'static_pages#landing_page'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
    validates :title, presence:true
    validates :description, presence:true, length: {:minimum => 5}

    def to_s
        title
    end
    belongs_to :user
    has_rich_text :description

    extend FriendlyId
    friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable, :trackable
           
    def to_s
      email
    end
    
    has_many :courses
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    if params[:title]
      @courses = Course.where('title ILIKE ?', "%#{params[:title]}%") #case-insensitive
    else
      @courses = Course.all
    end
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end


    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:landing_page]
  def landing_page
    @courses = Course.all.limit(3)
    @recent_courses = Course.all.limit(3).order(created_at: :desc)
  end

  def privacy_policy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all.order(created_at: :desc)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_course.html.haml
.card{:style => "width: 18rem;
    display: inline-block;"}
  .card-header
    .fa.fa-book
    = link_to course.title, course_path(course)
  .card-body
    = course.description
  .card-footer
    .far.fa-clock
    = course.created_at.strftime('%d-%b-%Y')
    .row
    .fa.fa-chalkboard-teacher
    = course.user
  .card-footer
    = link_to 'Show', course, class: 'btn btn-sm btn-primary'
    = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning'
    = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :description


  .form-actions
    = f.button :submit, class:"btn btn-secondary"

app/views/courses/edit.html.haml
.card
    .card-header
        %h1 Editing course
    .card-body
        = render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
%h1
  Courses:
  = @courses.count

.card-columns
  - @courses.each do |course|
    = render 'courses/course', course: course


%br

app/views/courses/new.html.haml
.card
    .card-header
        %h1.trix-content New course
    .card-body
        = render 'form'

= link_to 'Back', courses_path, class:"btn btn-warning"

app/views/courses/show.html.haml
%p#notice= notice
= link_to 'Courses', courses_path
\/
= link_to @course, course_path(@course)
%hr
= render 'courses/course', course: @course

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %script{:crossorigin => "anonymous", :src => "https://kit.fontawesome.com/b8fca9ea41.js"}
    %title UdemyClone2
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  %body
    = render 'static_pages/header'
    = render 'layouts/messages'
    .container
      = yield

app/views/static_pages/_header.html.haml
- if current_user
  = current_user.email
  %nav.navbar.navbar-expand-lg.bg-light
    .container-fluid
      %a.navbar-brand{:href => "#"} Udemy Clone
      %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        %ul.navbar-nav.me-auto.mb-2.mb-lg-0
          %li.nav-item
            %a.nav-link.active{"aria-current" => "page", :href => "#"}
              = link_to root_path, class:"btn btn-success" do
                %i.fa-solid.fa-house
          %li.nav-item
            %a.nav-link{:href => "#"}
              = link_to courses_path, class:"btn btn-secondary" do
                %i.fa-solid.fa-book
                Courses
          %li.nav-item
            %a.nav-link{:href => "#"}
              = link_to users_path, class:"btn btn-secondary" do
                %i.fa-solid.fa.fa-user
                Users
          %li.nav-item
            %a.nav-link{:href => "#"}
              = link_to new_course_path, class:"btn btn-secondary" do
                %i.fa-solid.fa-plus
                New Course
          %li.nav-item.dropdown
            %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
              Dropdown
            %ul.dropdown-menu
              %li
                %a.dropdown-item{:href => "#"} 
                  = link_to 'Account Settings', edit_user_registration_path 
              %li
                %a.dropdown-item{:href => "#"} Another action
              %li
                %hr.dropdown-divider/
              %li
                %a.dropdown-item{:href => "#"}
                  = link_to 'Sign Out', destroy_user_session_path, method: :delete
          %li.nav-item
            %a.nav-link{:href => "#"}
              = link_to 'Sign Out', destroy_user_session_path, method: :delete
        %form.d-flex{:role => "search"}
          = form_tag(courses_path, method: :get) do
            .input-group
              = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
              %button.btn.btn-outline-success{:type => "submit"} Search
- else
  = link_to 'Sign up', new_user_registration_path
  = link_to 'Log in', new_user_session_path

app/views/static_pages/landing_page.html.haml
.jumbotron
  .display-4
    What do you want to learn today?
  %br
  %form.d-flex{:role => "search"}
    = form_tag(courses_path, method: :get) do
      .input-group
        = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
        %button.btn.btn-outline-success{:type => "submit"} Search
  %br
  = link_to "Privacy Policy", privacy_policy_path, class: "btn btn-secondary"

.card-group
  .card.card-body
    %h1
      .fa.fa-graduation-cap
    = Course.count
    online courses
    .row
    Explore a variety of fresh topics
  .card.card-body
    %h1
      .fa.fa-chalkboard-teacher
      /.fa.fa-brain
    = Course.distinct.count(:user_id)
    expert instructors
    .row
    Find the right instructor for you
  .card.card-body
    %h1
      .fa.fa-user-graduate
    = User.count
    active learners
    .row
    Join the knowledge sharing community
  .card.card-body
    %h1
      .fa.fa-infinity
    Lifetime access
    .row
    Learn on your schedule


%hr
%h2
  Popular Courses
  %h6
    .card-columns
    - @courses.each do |course|
      = render 'courses/course', course: course
%hr
%h2
  Top Rated Courses
  %h6
    .card-columns
    - @courses.each do |course|
      = render 'courses/course', course: course
%hr
%h2
  Latest Courses
  %h6
    .card-columns
    - @recent_courses.each do |course|
      = render 'courses/course', course: course

app/views/static_pages/privacy_policy.html.haml
%h1
  Privacy Policy

app/views/users/_user.html.haml
.card
    .card-header
        .fa.fa-user
        Email:
        = user.email
    .card-footer
        Signed up
        = time_ago_in_words(user.created_at)
        ago
    .card-footer
        sign in count:
        = user.sign_in_count
        .row
        current sign in at:
        = user.current_sign_in_at
        .row
        last sign in at:
        = user.last_sign_in_at
        .row
        current sign in ip:
        = user.current_sign_in_ip
        .row
        last sign in ip:
        = user.last_sign_in_ip
        
        

app/views/users/index.html.haml
.card-columns
    - @users.each do |user|
        = render 'users/user', user: user